Add Hugo preset
aziontech/vulcan pull request #192
Opened 2023-12-09 15:59 UTC by tiagokrebs

Adding a new Hugo preset.  

About not using the `hugo` binary directly but through the package manager.
When you think about a typical Hugo site, the easiest example of dependencies are themes. But there’s something more fundamental to realize: Hugo itself is a dependency. The Hugo binary is a 3rd party library that is required for your application to work. If we could install Hugo locally as a dependency, we would have full control over the Hugo version used in our project. And best of all, all our project users would use the same version.  

The solution is to use a binary wrapper for Hugo with a package.json file already added. [hugo-bin](https://github.com/fenneclab/hugo-bin) is currently the most popular/accepted package.

2023-12-11 12:55 UTC, MagnunAVFAzion requested changes

2023-12-11 12:55 UTC, MagnunAVFAzion commented on lib/presets/custom/hugo/deliver/prebuild.js
> +  rm(outDir, { recursive: true, force: true });
We need to generate the manifest at the end of the prebuild step. You can copy this from https://github.com/aziontech/vulcan/blob/stage/lib/presets/custom/react/deliver/prebuild.js#L14 (lines 14-20) as this preset is purely static (deliver mode).

2023-12-11 14:10 UTC, jotanarciso commented on lib/presets/custom/hugo/deliver/prebuild.js
> +  await exec(`${command} hugo`, 'Hexo', true);
'Hexo' -> 'Hugo'

2024-02-03 17:31 UTC, tiagokrebs commented
@jotanarciso @MagnunAVFAzion Now we have one example of Hugo here too.

2024-02-05 16:05 UTC, jotanarciso approved these changes

2024-02-05 16:06 UTC, jotanarciso commented
Nice!

2024-02-06 12:44 UTC, MagnunAVFAzion approved these changes

2024-02-06 13:14 UTC, merged

2024-02-06 13:15 UTC, tiagokrebs commented
:tada: This PR is included in version 2.4.0-stage.2 :tada:

The release is available on:
- [npm package (@stage dist-tag)](https://www.npmjs.com/package/edge-functions/v/2.4.0-stage.2)
- [GitHub release](https://github.com/aziontech/vulcan/releases/tag/v2.4.0-stage.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-16 20:31 UTC, tiagokrebs commented
:tada: This PR is included in version 2.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/edge-functions/v/2.4.0)
- [GitHub release](https://github.com/aziontech/vulcan/releases/tag/v2.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: