refactor: init command
aziontech/vulcan pull request #266
Opened 2024-03-12 17:32 UTC by jotanarciso

2024-03-19 13:35 UTC, jcbsfilho submitted a review, later dismissed

2024-03-19 16:24 UTC, MagnunAVFAzion requested changes

2024-03-19 16:24 UTC, MagnunAVFAzion commented on lib/constants/framework-initializer.constants.js
> +  'C++': {
We must change the name to **Emscripten**. You can use multiple languages to code. From the docs:
`Compile your existing projects written in C or C++ — or any language that uses LLVM — to browsers, Node.js, or wasm runtimes.`

2024-03-19 16:48 UTC, MagnunAVFAzion approved these changes

2024-03-19 17:08 UTC, merged

2024-03-20 12:28 UTC, tiagokrebs commented
:tada: This PR is included in version 2.6.0-stage.8 :tada:

The release is available on:
- [npm package (@stage dist-tag)](https://www.npmjs.com/package/edge-functions/v/2.6.0-stage.8)
- [GitHub release](https://github.com/aziontech/vulcan/releases/tag/v2.6.0-stage.8)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: