feat: eleventy framework preset
aziontech/vulcan pull request #284
Opened 2024-03-28 14:58 UTC by PabloDiehl

Eleventy (or [11ty](https://www.11ty.dev)) is a SSG (static site generator).

2024-04-02 12:52 UTC, jcbsfilho commented
@PabloDiehl Firstly, the preset was very good.
All that was missing in the presets test unit was adding the expect for the preset.

Expected:

```js

// https://github.com/PabloDiehl/vulcan/blob/stage/lib/utils/presets/presets.utils.test.js#L10

const expectedOutput = [
   ...
      'eleventy',
   ...
    ];
    
// https://github.com/PabloDiehl/vulcan/blob/stage/lib/utils/presets/presets.utils.test.js#L77

const expectedResult = [
    ...
    'Eleventy (Deliver)',
    ...
  ];

```

2024-04-02 13:22 UTC, PabloDiehl commented
> @PabloDiehl Firstly, the preset was very good. All that was missing in the presets test unit was adding the expect for the preset.
> 
> Expected:
> 
> ```js
> // https://github.com/PabloDiehl/vulcan/blob/stage/lib/utils/presets/presets.utils.test.js#L10
> 
> const expectedOutput = [
>    ...
>       'eleventy',
>    ...
>     ];
>     
> // https://github.com/PabloDiehl/vulcan/blob/stage/lib/utils/presets/presets.utils.test.js#L77
> 
> const expectedResult = [
>     ...
>     'Eleventy (Deliver)',
>     ...
>   ];
> ```

Added the missing tests.

2024-04-02 13:31 UTC, jcbsfilho submitted a review, later dismissed
Nice!

2024-04-02 14:13 UTC, jotanarciso requested changes

2024-04-02 14:20 UTC, PabloDiehl commented on lib/presets/custom/eleventy/deliver/prebuild.js
> +const manifest = {
🤔 
Good question, probably we'll need this in production environment. ⚒️

2024-04-02 14:27 UTC, jotanarciso approved these changes

2024-04-02 14:28 UTC, jcbsfilho approved these changes

2024-04-02 16:15 UTC, merged

2024-04-02 16:17 UTC, tiagokrebs commented
:tada: This PR is included in version 2.6.0-stage.11 :tada:

The release is available on:
- [npm package (@stage dist-tag)](https://www.npmjs.com/package/edge-functions/v/2.6.0-stage.11)
- [GitHub release](https://github.com/aziontech/vulcan/releases/tag/v2.6.0-stage.11)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-04-19 14:43 UTC, tiagokrebs commented
:tada: This PR is included in version 2.6.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/edge-functions/v/2.6.0)
- [GitHub release](https://github.com/aziontech/vulcan/releases/tag/v2.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: