feat: add svelte preset
aziontech/vulcan pull request #292
Opened 2024-04-04 14:25 UTC by hendriksoares

2024-04-09 19:31 UTC, jcbsfilho commented on tests/e2e/svelte-static.test.js
> +    await page.goto(`${localhostBaseUrl}/`);
Before checking the content, it is necessary to wait for the render resolution.

```js
await page.goto(`${localhostBaseUrl}/`, {
    waitUntil: 'domcontentloaded',
});
await page.waitForSelector('h1');
const pageContent = await page.content();

```

2024-04-09 19:34 UTC, jcbsfilho commented on tests/e2e/svelte-static.test.js
> +    expect(pageContent).toContain(
Content contains html tags, please validate text or insert tags.

```js

expect(pageContent).toContain('kit.svelte.dev');

```

2024-04-09 19:34 UTC, jcbsfilho commented on tests/e2e/svelte-static.test.js
> +  test('Should render edge page in "/edge" route', async () => {
This route does not exist in the example

2024-04-09 19:35 UTC, jcbsfilho commented on tests/e2e/svelte-static.test.js
> +      .get('/favicon.ico')
The favicon is png.

```js
await request
      .get('/favicon.png')
      .expect(200)
      .expect('Content-Type', /image\/png/);

```

2024-04-09 19:38 UTC, jcbsfilho requested changes

2024-04-09 19:38 UTC, jcbsfilho commented on tests/e2e/svelte-static.test.js
> +    await page.goto(`${localhostBaseUrl}/edge`);
Please add wait

```js
await page.goto(`${localhostBaseUrl}/`, { waitUntil: 'domcontentloaded', });
```

2024-04-16 14:59 UTC, jotanarciso approved these changes

2024-04-16 15:30 UTC, enicio approved these changes

2024-04-16 17:36 UTC, merged

2024-04-16 17:37 UTC, tiagokrebs commented
:tada: This PR is included in version 2.6.0-stage.14 :tada:

The release is available on:
- [npm package (@stage dist-tag)](https://www.npmjs.com/package/edge-functions/v/2.6.0-stage.14)
- [GitHub release](https://github.com/aziontech/vulcan/releases/tag/v2.6.0-stage.14)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-04-19 14:43 UTC, tiagokrebs commented
:tada: This PR is included in version 2.6.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/edge-functions/v/2.6.0)
- [GitHub release](https://github.com/aziontech/vulcan/releases/tag/v2.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: