feat(presets): vitepress
aziontech/vulcan pull request #356
Opened 2024-07-12 13:22 UTC by PabloDiehl

Adding a new preset for VitePress-based applications.

<img width="704" alt="Screenshot 2024-07-12 at 10 04 05" src="https://github.com/user-attachments/assets/1a716b4b-2146-4fb3-a4cf-39283054d314">

This PR relates to:
- https://github.com/aziontech/vulcan-examples/pull/55
- https://github.com/aziontech/azion-samples/pull/112

2024-07-12 13:24 UTC, maxwelbm approved these changes

2024-07-12 13:27 UTC, rodrigomaria approved these changes

2024-07-12 17:10 UTC, jcbsfilho commented
@PabloDiehl Please change the base to `stage`

2024-07-12 17:12 UTC, jcbsfilho requested changes
Please, you need to add the preset tests in: 

`lib/utils/presets/presets.utils.test.js`

`getPresetsList utils › Should get the list of presets based on type`
  
 `getPresetsList utils › Should list presets beatified`

2024-07-12 17:31 UTC, jcbsfilho approved these changes

2024-07-12 17:32 UTC, MagnunAVFAzion approved these changes

2024-07-12 17:34 UTC, merged

2024-07-15 18:35 UTC, tiagokrebs commented
:tada: This PR is included in version 2.12.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/edge-functions/v/2.12.0)
- [GitHub release](https://github.com/aziontech/vulcan/releases/tag/v2.12.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: